databases:
  - name: draw_together_backend
    databaseName: draw_together_backend_production
    user: draw_user

services:
  - type: web
    name: draw_together_backend
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: draw_together_backend_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
